# Generated by Django 3.2.13 on 2023-02-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.BigAutoField(db_column='circuitId', primary_key=True, serialize=False)),
                ('circuitref', models.CharField(db_column='circuitRef', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'db_table': 'circuits',
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.BigAutoField(db_column='constructorId', primary_key=True, serialize=False)),
                ('constructorref', models.CharField(db_column='constructorRef', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Constructor',
                'verbose_name_plural': 'Constructors',
                'db_table': 'constructors',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.CharField(db_column='driverId', max_length=255, primary_key=True, serialize=False)),
                ('driverref', models.CharField(db_column='driverRef', max_length=255, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(db_column='url', max_length=512, unique=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.BigAutoField(db_column='raceId', primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fp1_date', models.DateField(blank=True, null=True)),
                ('fp1_time', models.TimeField(blank=True, null=True)),
                ('fp2_date', models.DateField(blank=True, null=True)),
                ('fp2_time', models.TimeField(blank=True, null=True)),
                ('fp3_date', models.DateField(blank=True, null=True)),
                ('fp3_time', models.TimeField(blank=True, null=True)),
                ('quali_date', models.DateField(blank=True, null=True)),
                ('quali_time', models.TimeField(blank=True, null=True)),
                ('sprint_date', models.DateField(blank=True, null=True)),
                ('sprint_time', models.TimeField(blank=True, null=True)),
                ('circuitid', models.ForeignKey(db_column='circuitId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.circuits')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('year', models.IntegerField(db_column='year', primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.BigAutoField(db_column='statusId', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Sprintresults',
            fields=[
                ('sprintresultid', models.BigAutoField(db_column='sprintResultId', primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(db_column='positionText', max_length=255)),
                ('positionorder', models.IntegerField(db_column='positionOrder')),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, db_column='fastestLap', null=True)),
                ('fastestlaptime', models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.constructors')),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
                ('statusid', models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.status')),
            ],
            options={
                'verbose_name': 'Sprint Result',
                'verbose_name_plural': 'Sprint Results',
                'db_table': 'sprintResults',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.BigAutoField(db_column='resultId', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(db_column='positionText', max_length=255)),
                ('positionorder', models.IntegerField(db_column='positionOrder')),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, db_column='fastestLap', null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestlaptime', models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True)),
                ('fastestlapspeed', models.CharField(blank=True, db_column='fastestLapSpeed', max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.constructors')),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
                ('statusid', models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.status')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='races',
            name='year',
            field=models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.seasons'),
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.BigAutoField(db_column='qualifyId', primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.constructors')),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Qualifying',
                'verbose_name_plural': 'Qualifyings',
                'db_table': 'qualifying',
            },
        ),
        migrations.CreateModel(
            name='Driverstandings',
            fields=[
                ('driverstandingsid', models.BigAutoField(db_column='driverStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Driver Standing',
                'verbose_name_plural': 'Driver Standings',
                'db_table': 'driverStandings',
            },
        ),
        migrations.CreateModel(
            name='Constructorstandings',
            fields=[
                ('constructorstandingsid', models.BigAutoField(db_column='constructorStandingsId', primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.constructors')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Constructor Standing',
                'verbose_name_plural': 'Constructor Standings',
                'db_table': 'constructorStandings',
            },
        ),
        migrations.CreateModel(
            name='Constructorresults',
            fields=[
                ('constructorresultsid', models.BigAutoField(db_column='constructorResultsId', primary_key=True, serialize=False)),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorid', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.constructors')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Constructor Result',
                'verbose_name_plural': 'Constructor Results',
                'db_table': 'constructorResults',
            },
        ),
        migrations.CreateModel(
            name='Pitstops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Pitstop',
                'verbose_name_plural': 'Pitstops',
                'db_table': 'pitStops',
                'unique_together': {('raceid', 'driverid', 'stop')},
            },
        ),
        migrations.CreateModel(
            name='Laptimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverid', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.drivers')),
                ('raceid', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.DO_NOTHING, to='formula1.races')),
            ],
            options={
                'verbose_name': 'Lap Time',
                'verbose_name_plural': 'Lap Times',
                'db_table': 'lapTimes',
                'unique_together': {('raceid', 'driverid', 'lap')},
            },
        ),
    ]
